// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rafmgnrndpotcfuaairp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZm1nbnJuZHBvdGNmdWFhaXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Njk2NjgsImV4cCI6MjA3MDQ0NTY2OH0.VIl4AO1o7FJjerVnyZMsh4xblwP1v4ROYuSq9RkbBzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});